apiVersion: v1
kind: Service
metadata:
  name: medicos-service
  namespace: ips
spec:
  type: NodePort
  selector:
    app: medicos # Debe ser igual al 'app' del deployment
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30008 # Entrarás por http://localhost:30008